from Model.City import City
from Model.Place import Place
from Model.Direction import Direction
from Model.Chowki import Chowki
from Model.Camera import Camera
from Model.CameraChowki import CameraChowki
from Model.Shift import Shift
from Model.TrafficWarden import TrafficWarden
from Model.Configure import db,app