from Model.City import City
from Model.Place import Place
from Model.Direction import Direction
from Model.Chowki import Chowki
from Model.Camera import Camera
from Model.CameraChowki import CameraChowki
from Model.Shift import Shift
from Model.TrafficWarden import TrafficWarden
from Model.WadenChowki import WardenChowki
from Model.User import User
from Model.Violation import Violation
from Model.ViolationFine import ViolationFine
from Model.Vehicle import Vehicle
from Model.ViolationHistory import ViolationHistory
from Model.ViolationDetails import ViolationDetails
from Model.Challan import Challan
from Model.ChallanViolations import ChallanViolations
from Model.Configure import db,app