from Controller.LocationController import LocationController
from Controller.CameraChowkiController import CameraChowkiController
from Controller.WardenChowkiController import WardenChowkiController
from Controller.ChallanController import ChallanController
from Controller.YoloController import yolov8